### ISSUE TITLE
Make installation easier

### ISSUE THREAD

**Issue by stevenharman** [versionone/git-hooks#2]
requiring manual download and copying of files sucks. the bash script to cURL things down is better, but still sucks from a maintainability angle.

How about a simple Ruby script, install.rb, that we cURL/Wget, and execute to do the installation. it could create any necessary directories, clean up old files, set permissions, etc.

**Comment by jallers** [comment]
I'm not sure what's desired in the ruby world. It may serve us in the node.js world to consider husky.js and node modules.
